#!/bin/python

import os

Import('env')

src_files = ['t_direction.cpp', 't_lattice.cpp']
i = 0
#print src_files
for src in src_files:
    env.Program('tes' + src, src, LIBS = ['saw'], LIBPATH='#/build/')
    i += 1
