#!/bin/python

import os

Import('env')

src_files = ['t_direction.cpp']
i = 0
#print src_files
for src in src_files:
    env.Program('test' + str(i), src, LIBS = ['saw'], LIBPATH='#/build/')
    i += 1
